### ISSUE TITLE
萌娘百科又双寄了

### ISSUE THREAD

**Issue by liuzj288** [ZombieFly/nb2-wiki#13]
![image](https://user-images.githubusercontent.com/13833404/197818807-de2e3917-b341-4c30-82d7-f5a7d9d77c02.png)

**Comment by ZombieFly** [comment]
> ![image](https://user-images.githubusercontent.com/13833404/197818807-de2e3917-b341-4c30-82d7-f5a7d9d77c02.png)
> 

萌百现在全站503关服维护，自然无法访问，只能等他自己再开放。
