### ISSUE TITLE
START_COMMAND留空时子命令无法执行

### ISSUE THREAD

**Issue by BENDIT233** [ZombieFly/nb2-wiki#17]
rt，.env文件中`START_COMMAND=[""]`时，子命令无法执行

**Comment by ZombieFly** [comment]
执行子命令前，会检查主命令后第一个字符是否被包括于 `command_start` 中：
```Python
if keywd[0] in get_driver().config.command_start:
```
如果 `command_start` 中只有一个`""` 确实会出现无法使用子命令的情况，可以尝试在  `command_start` 中再添加一个命令头，以确保子命令可以触发。

**Comment by BENDIT233** [comment]
非常感谢！！！祝您新年快乐，阖家幸福！！

**Comment by ZombieFly** [comment]
目前子命令与主命令的分割还是使用设定的 `COMMAND_START` ，或许可以独立读取 `COMMAND_SEP` ？
