### ISSUE TITLE
我想在我的插件里面调用nb-wiki

### ISSUE THREAD

**Issue by QwindF** [ZombieFly/nb2-wiki#18]
起因是我想在mc（可以直接在服务器里调用命令）里写个wiki，
发现有现成的，那就直接抄吧XD（我调用output里的代码）
但是写完之后发现出来了些莫名其妙的东西，
我也看到了注释`# ! 目前重定向可能会出现完全不相干的结果返回`
没看明白怎么处理的，请问怎么解决

**Comment by QwindF** [comment]
应该是调用了wiki.summary

**Comment by ZombieFly** [comment]
因为是调用的`mediawiki api`，`mediawiki api` 的搜索功能本身也不大聪明

**Comment by QwindF** [comment]
![image](https://github.com/ZombieFly/nb2-wiki/assets/87116340/eb1a2da5-84c1-4e40-b558-5a915de03012)
![image](https://github.com/ZombieFly/nb2-wiki/assets/87116340/910a143e-fa63-45cc-8aef-bce64df4d9c5)

**Comment by QwindF** [comment]
请问一下原项目是怎么实现的
![E4JVK QJ_ID`G~59RDQG%F3](https://github.com/ZombieFly/nb2-wiki/assets/87116340/ff53deef-3d38-4fa4-8efa-8dec86fa2132)
翻代码看得不是很懂

**Comment by ZombieFly** [comment]
> ![image](https://github.com/ZombieFly/nb2-wiki/assets/87116340/eb1a2da5-84c1-4e40-b558-5a915de03012)
> ![image](https://github.com/ZombieFly/nb2-wiki/assets/87116340/910a143e-fa63-45cc-8aef-bce64df4d9c5)
> 
> 

你这生成的简介多少有些奇怪了，应该不是 mc wiki的。

**Comment by ZombieFly** [comment]
![Screenshot_2023-08-06-13-49-07-347_mark.via.jpg](https://github.com/ZombieFly/nb2-wiki/assets/60338092/32551349-d670-4ce1-9645-af3523210fa6)

破案，是萌百

**Comment by ZombieFly** [comment]
```python
outstr = await output(title=keywd, mwiki=state['mwiki'] if state.__contains__('mwiki') else RAW_MWIKI, redirect=True, msg_id=msg_id)
```
在发起搜索时会从会话里获取目标wiki的各种配置信息。
可以参考 `data.py` 的多配置实现，但如果你是直接调用 `Wikipedia` 模块，可以查看最新的（刚刚）[提交记录](https://github.com/ZombieFly/nb2-wiki/commit/930c760ae4ff524008950366104038aa6d2cda27)。

**Comment by QwindF** [comment]
好的，原来是这样
