### ISSUE TITLE
萌娘百科这个词条抓取失败

### ISSUE THREAD

**Issue by liuzj288** [ZombieFly/nb2-wiki#5]
https://zh.moegirl.org.cn/zh-hans/%E5%88%BB%E6%99%B4

![image](https://user-images.githubusercontent.com/13833404/181189335-56608f8a-c546-4c19-99f1-6c9cb0f80a89.png)

**Comment by liuzj288** [comment]
萌娘百科只能精确匹配搜索结果，比如
![image](https://user-images.githubusercontent.com/13833404/181192451-43d6a049-c6ff-47dd-8d5b-67c3b615d660.png)
https://zh.moegirl.org.cn/zh-hans/%E8%B5%AB%E6%95%8F
这个歧义页没有匹配会报错且没有返回信息
![image](https://user-images.githubusercontent.com/13833404/181192772-ab7f4ac2-ca0d-4664-9455-4cec7cb79880.png)
![image](https://user-images.githubusercontent.com/13833404/181192892-867e73ea-9dbc-430b-94ff-bb6d6a9cc676.png)

**Comment by ZombieFly** [comment]
> https://zh.moegirl.org.cn/zh-hans/%E5%88%BB%E6%99%B4
> 
> ![image](https://user-images.githubusercontent.com/13833404/181189335-56608f8a-c546-4c19-99f1-6c9cb0f80a89.png)

通常此报错是由于超时引发的，刚经本地测试，可以正常返回结果
![V%VM8736_)~3GI1ZNZVK%78](https://user-images.githubusercontent.com/60338092/181207584-3f8bbedb-22e1-4cda-a8aa-70aedb8c2e60.png)
但仍然感谢你的报告，已将优化超时处理纳入日程

**Comment by ZombieFly** [comment]
> 萌娘百科只能精确匹配搜索结果，比如 ![image](https://user-images.githubusercontent.com/13833404/181192451-43d6a049-c6ff-47dd-8d5b-67c3b615d660.png) https://zh.moegirl.org.cn/zh-hans/%E8%B5%AB%E6%95%8F 这个歧义页没有匹配会报错且没有返回信息 ![image](https://user-images.githubusercontent.com/13833404/181192772-ab7f4ac2-ca0d-4664-9455-4cec7cb79880.png) ![image](https://user-images.githubusercontent.com/13833404/181192892-867e73ea-9dbc-430b-94ff-bb6d6a9cc676.png)

非常感谢报告此问题！由于本人的疏忽而引发了此问题，现已修复，见
https://github.com/ZombieFly/nb2-wiki/commit/d8157e0d28389f4636deccc7e15402f53ed1c7cc
