### ISSUE TITLE
更新之后直接报错

### ISSUE THREAD

**Issue by liuzj288** [ZombieFly/nb2-wiki#7]
![image](https://user-images.githubusercontent.com/13833404/181411415-a38fe07d-cc06-49c3-9b21-044c78c4ada3.png)

**Comment by ZombieFly** [comment]
json库内报错请说明一下环境，如json库版本

**Comment by ZombieFly** [comment]
这是说明请求返回的json格式错误,请使用`.wiki.lsl wiki记录名`命令获得wiki记录信息，并发送至此issue，此外请说明一下出现报错时使用的搜索关键词

**Comment by liuzj288** [comment]
> wiki.lsl wiki记录名

找到原因了，你readme里面这个不能用的，更新之后我直接抄的这个所以报错了，得用https://zh.moegirl.org.cn/api.php
![image](https://user-images.githubusercontent.com/13833404/181452756-021bea46-1f7b-4827-9d53-423e736a0a42.png)

模糊搜索时输出了额外的内容

![image](https://user-images.githubusercontent.com/13833404/181453297-e6983289-9d12-457f-8c62-133325b1cdf9.png)

**Comment by ZombieFly** [comment]
> > wiki.lsl wiki记录名
> 
> 找到原因了，你readme里面这个不能用的，更新之后我直接抄的这个所以报错了，得用https://zh.moegirl.org.cn/api.php ![image](https://user-images.githubusercontent.com/13833404/181452756-021bea46-1f7b-4827-9d53-423e736a0a42.png)

萌百有对访问次数的限制，readme中的api实际是萌百手机app请求时的api，UA亦是，主要是为了避免被拦截，不过直接请求网页站点的api，只要频率不至于太高，也不会产生问题。

至于你反应无法此api使用，经测试，此api返回了`fault filter abort`，系萌百自己的操作，至于以后能不能用咱也不知道了。
